version: "3"
services:
  comexio_postgres:
    image: postgres:latest
    container_name: comexio_postgres
    privileged: true
    restart: always
    shm_size: '10gb'
    environment:
      POSTGRES_PASSWORD: "api"
    ports:
      - "25432:5432"
    volumes:
      - ./devops/database/postgresql/data:/var/lib/postgresql/data
      - ./devops/database/postgresql/postgresql_servidor_16_gb.conf:/var/lib/postgresql/data/postgresql.conf
      - ./storage:/storage

  comexio_php:
    image: www.expectv.com.br:5000/expectv/php:datasync_8
    container_name: comexio_php
    privileged: true
    restart: always
    platform: linux/amd64
    ports:
      - "9500:9000"
    volumes:
      - .:/app
      - ./devops/php/php-development.ini:/usr/local/etc/php/conf.d/additional.ini
      - ./devops/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./devops/php/assets/api_php.conf:/etc/supervisor/conf.d/api_php.conf
      - ./devops/php/assets/crontab:/etc/cron.d/crontab
    env_file:
      - .env-docker
    command: ./devops/php/assets/app.sh

  comexio_nginx:
    image: www.expectv.com.br:5000/expectv/nginx:v1
    depends_on:
      - comexio_php
    container_name: comexio_nginx
    privileged: true
    restart: always
    ports:
      - "8005:80"
    volumes:
      - .:/app
      - ./devops/nginx/default-prod.conf:/etc/nginx/conf.d/default.conf

  comexio_redis:
    image: www.expectv.com.br:5000/expectv/redis:v1
    container_name: 'comexio_redis'
    restart: 'always'
    volumes:
      - ./devops/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6381:6379
    command: "redis-server /usr/local/etc/redis/redis.conf"

networks:
    default: ~
